version: "3"

services:
  searxng:
    image: searxng/searxng
    container_name: searxng
    ports:
      - "4000:8080"
    environment:
      - BASE_URL=http://localhost:4000/
      - SEARXNG_PUBLIC=True
      - AUTOCOMPLETE=duckduckgo
    command: >
      bash -c "sed -i '/use_x_forwarded_for/d' /etc/searxng/settings.yml &&
               sed -i '/rate_limit/d' /etc/searxng/settings.yml &&
               searxng-run"
